### PR TITLE
Introduce string set handling

### LINKED ISSUE #33: Allow single object as parameter to query a set/list
My entity contains a field of type Set<String> countries (stringSet). I want to query against it with one country.

## Expected Behavior

`Iterable<ProductEntity> findAllByCountriesContainsOrCountriesContains(String country)` returns a list of products, that contains `country` their `countries` fields.

## Actual Behavior

```
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.Collection (java.lang.String and java.util.Collection are in module java.base of loader 'bootstrap')
	at com.amazonaws.services.dynamodbv2.datamodeling.StandardTypeConverters$Vector$ToSet$1.convert(StandardTypeConverters.java:449) ~[aws-java-sdk-dynamodb-1.11.415.jar:na]
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverter$DelegateConverter.convert(DynamoDBTypeConverter.java:104) ~[aws-java-sdk-dynamodb-1.11.415.jar:na]
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverter$NullSafeConverter.convert(DynamoDBTypeConverter.java:123) ~[aws-java-sdk-dynamodb-1.11.415.jar:na]
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverter$ExtendedConverter.convert(DynamoDBTypeConverter.java:83) ~[aws-java-sdk-dynamodb-1.11.415.jar:na]
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.convert(DynamoDBMapperFieldModel.java:138) ~[aws-java-sdk-dynamodb-1.11.415.jar:na]
	at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQueryCriteria.getPropertyAttributeValue(AbstractDynamoDBQueryCriteria.java:557) ~[spring-data-dynamodb-5.2.4.jar:5.2.4]
	at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQueryCriteria.createSingleValueCondition(AbstractDynamoDBQueryCriteria.java:706) ~[spring-data-dynamodb-5.2.4.jar:5.2.4]
	at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQueryCriteria.withSingleValueCriteria(AbstractDynamoDBQueryCriteria.java:485) ~[spring-data-dynamodb-5.2.4.jar:5.2.4]
	at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQueryCreator.addCriteria(AbstractDynamoDBQueryCreator.java:151) ~[spring-data-dynamodb-5.2.4.jar:5.2.4]
	at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQueryCreator.create(AbstractDynamoDBQueryCreator.java:123) ~[spring-data-dynamodb-5.2.4.jar:5.2.4]
	at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQueryCreator.create(AbstractDynamoDBQueryCreator.java:49) ~[spring-data-dynamodb-5.2.4.jar:5.2.4]
```	
## Specifications
  
  - Spring Data DynamoDB Version: 5.2.4 (2.2)
  - Spring Data Version: 2.3.1.RELEASE
  - AWS SDK Version: 1.11.415
  - Java Version: 11.0.2 - OpenJDK 64-Bit Server VM 11.0.2+9
  - Platform Details: Mac OS X 10.15.4

### PR DESCRIPTION
**Pull request by hannes-angst**
(1) Implements handling of CONTAINS on SS (string set) and NOT_CONTAINS on SS (string set).
(2) Fixes object mis-match for collection parameters on SS (string set) properties.

### CODE REVIEW

**Comment by boostchicken** [comment]
Wow @hannes-angst , I was working on this myself.  You beat me to the punch.  Will test and merge here in a bit

**Comment by boostchicken** [comment]
Did you need this released to central anytime soon?

**Comment by boostchicken** [comment]
Oh @hannes-angst can you make the PR goto develop please?

**Review by boostchicken — APPROVED** [review]

**Comment by hannes-angst** [comment]
> Did you need this released to central anytime soon?

Would be nice. ❤️

**Comment by boostchicken** [comment]
Are you planning on adding any other contributions? If not I can cut 5.2.5 with your additions now.

**Comment by hannes-angst** [comment]
I was looking into the OR challenge but I identified at least three major reworks
- updated to dynamodb library 2
- move from query criteria to filter expressions
- part tree processing rewrite 😢 

So I would suggest to just wrap it up and call it a 5.2.5 ;)

**Comment by boostchicken** [comment]
So if we move to DynamoDB 2, might as well jsut re-write it from the ground up.  I have used their new EnhancedMapper and it's great, however, nothing here would really carry over all that much.  There are years of tech debt and old spring conventions built up here. It is probably time to start fresh.

Is this something you are interested in working on?  I want to do it, but to do it by myself would take god knows how long

As far as filter expressions, you will noticed I wrote an ugly hack to get in there quickly using the @Query annotation.  Again, it's such a fundamental switch that it would require a large re-write :)

**Comment by boostchicken** [comment]
@hannes-angst It has been released and is synced on central.
https://repo1.maven.org/maven2/io/github/boostchicken/spring-data-dynamodb/5.2.5/

I don't know if you are using it over at Porsche, but if you are I might to upgrade my 991 C2S to utilize whatever service it is powering :)

**Comment by hannes-angst** [comment]
991 C2S is a beauty. I would love to own a Porsche Taycan Turbo 4S 😂 

I was baffled that there is no spring repository support directly from AWS and I hate to wait for testcontainers to come up with a local dynamodb instance just to do things I already know are working 😉.

For the rewrite, there would be some things to tackle:
- Walk the parts tree to come up with the expression filter we need (see below).
- Workaround the limitations of dynamo DB (SS contains with multiple elements)
- Decide when to query (hash or index) and when to scan (would be awesome if we could determine this from the entity definition and/or the table)
- Ordering (don't know if this is even possible in dynamoDB between pages)
- Not sure how ORM works with v2. (Have to research this further 🤔)

I'm pretty sure there is much more to consider and I can totally feel you not to go solo on it.
I can have a look at the parts tree stuff. This seems easy to grasp 🤥 😉

Scans:
```
 ScanRequest scan = ScanRequest.builder()
                .tableName("User")
                .filterExpression("contains(#key1, :value1) AND contains(#key2, :value2) AND #key3 = :value3")
                .expressionAttributeNames(Map.of(
                        "#key1", "tags",
                        "#key2", "tags",
                        "#key3", "postCode"))
                .expressionAttributeValues(Map.of(
                        ":value1", AttributeValue.builder().s("tag-a").build(),
                        ":value2", AttributeValue.builder().s("tag-b").build(),
                        ":value3", AttributeValue.builder().s("1234").build()
                )).build();
```

Queries:
```
        QueryRequest query = QueryRequest.builder()
                .tableName(tableName)
                .keyConditionExpression("#key1 = :value1")
                .expressionAttributeNames(Map.of(
                        "key1", "id"))
                .expressionAttributeValues(Map.of(
                        "value1", AttributeValue.builder().s("4711").build())).build();
```

**Comment by boostchicken** [comment]
https://github.com/boostchicken/spring-data-dynamodb/wiki/Change-Log

Check that page for how the library handles filters right now.  I know its kind of jankey but with out the mechanism to decide when to query or scan, this is the best I could do on my timeline. It would be great to re-write the Part Tree and GSI code to figure out when a GSI is available and when it would require filters as opposed to queries

https://aws.amazon.com/blogs/developer/introducing-enhanced-dynamodb-client-in-the-aws-sdk-for-java-v2/

That is the library that replaces DynamoDBMapper.  I moved one of my apps from this project to that.  If you are interested in seeing an actual in-depth production implementation let me know and we can set up a screen share (can't make the code public).  While there are some similarities, there is not enough to make me want to carry all this code forward.

**Comment by hannes-angst** [comment]
@boostchicken Any way to chat with you?

**Comment by hannes-angst** [comment]
I created a [branch](https://github.com/hannes-angst/spring-data-dynamodb) that uses the current code and add expression filters to the queries. This will allow for advanced -- scan -- queries.
This is definitively WIP since I need to add much more test cases. 😁

**Comment by boostchicken** [comment]
@hannes-angst Are you on discord? boostchicken#3135.  We can also setup a Slack

**Comment by boostchicken** [comment]
@hannes-angst 
https://join.slack.com/t/boostchicken/shared_invite/zt-fcjszaw4-2ZuNFxIQnrpjxixnm17LXQ

**Pull request merged**
